networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.171.0/24
          gateway: 192.168.171.1
services:
  captain:
    image: elixir:latest
    user: "${UID}:${GID}"
    hostname: captain
    working_dir: /home/edtm
    command: _build/dev/rel/server/bin/server start
    networks:
      - internal
    volumes:
      - ./src:/home
    stdin_open: true # docker run -i
    tty: true # docker run -t
    env_file: ".env"
  conscript1:
    image: elixir:latest
    user: "${UID}:${GID}"
    hostname: conscript1
    depends_on:
      - captain
    working_dir: /home/edtm
    command: _build/dev/rel/client/bin/client start
    networks:
      - internal
    volumes:
      - ./src:/home
    stdin_open: true # docker run -i
    tty: true # docker run -t
    env_file: ".env"
    environment:
      - CAPTAIN_HOSTNAME=captain
  conscript2:
    image: elixir:latest
    user: "${UID}:${GID}"
    hostname: conscript2
    depends_on:
      - captain
    working_dir: /home/edtm
    command: _build/dev/rel/client/bin/client start
    networks:
      - internal
    volumes:
      - ./src:/home
    stdin_open: true # docker run -i
    tty: true # docker run -t
    env_file: ".env"
    environment:
      - CAPTAIN_HOSTNAME=captain
